on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Name of the user that starts the workflow'
        required: true
        default: 'Paolo Salvatori'
      location:
        description: 'Azure region where deploy resources'
        required: true
        default: 'WestEurope'

name: Metering Infra ARM Template Deployment
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      # Print user name
    - run: |
        echo "Workflow started by " ${{ github.event.inputs.username }}

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_INFRA_RG }}
        template: ./arm/templates/infra/azuredeploy.json
        parameters: ./arm/templates/infra/azuredeploy.parameters.json location=${{ github.event.inputs.location }}

      # output containerName variable from template
    - run: echo "FunctionAppName=${{ steps.deploy.outputs.functionAppName }}"
