# This Docker Compose file locally runs the latest metered-billing-accelerator build from GitHub.
version: '3.4'
services:
  metered-billing-accelerator-main:
    image: ghcr.io/microsoft/metered-billing-accelerator:main
    environment:
      - AZURE_METERING_MARKETPLACE_TENANT_ID
      - AZURE_METERING_MARKETPLACE_CLIENT_ID
      - AZURE_METERING_MARKETPLACE_CLIENT_SECRET
      - AZURE_METERING_INFRA_TENANT_ID
      - AZURE_METERING_INFRA_CLIENT_ID
      - AZURE_METERING_INFRA_CLIENT_SECRET
      - AZURE_METERING_INFRA_CHECKPOINTS_CONTAINER
      - AZURE_METERING_INFRA_SNAPSHOTS_CONTAINER
      - AZURE_METERING_INFRA_EVENTHUB_NAMESPACENAME
      - AZURE_METERING_INFRA_EVENTHUB_INSTANCENAME
      - AZURE_METERING_INFRA_CAPTURE_FILENAME_FORMAT
      - AZURE_METERING_INFRA_CAPTURE_CONTAINER
      - AZURE_METERING_MAX_DURATION_BETWEEN_SNAPSHOTS
      - AZURE_METERING_MAX_NUMBER_OF_EVENTS_BETWEEN_SNAPSHOTS
